contact: dipo@ebi.ac.uk
contributors: null
creators: Olamidipupo Ajigboye
edit_format: owl
github_org: S2Ola
id: scao
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: cl
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
obo_format_options: ''
pattern_group: null
reasoner: ELK
repo: scao
report_fail_on: null
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: Single Cell Atlas Ontology
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: false
